
const Mystery = [
    {
        id: 1,
        title: 'Babylon',
        image: 'babylon.jpg',
        genre: ['Mystery', 'Suspense'],
        episodes: 12,
        rating: 6.75,
        type: 'TV',
        gif: 'babylon.gif',
        cruncyroll: 'https://animepahe.com/anime/0af68ad7-89bd-f8fc-8c96-fcc2e8e5ba79',
        youtube: 'https://www.youtube.com/watch?v=lmwuU8MTa9Q&ab_channel=phantomsword',
        description: 'Babylon is a thought-provoking and intense anime that follows a prosecutor who becomes embroiled in a controversial political conspiracy. With its complex themes, well-developed characters, and shocking twists, this anime offers a gripping exploration of power, justice, and the corrupting influence of politics.',
        url: 'https://myanimelist.net/anime/37525/Babylon',
    },

    {
        id: 2,
        title: 'Darker than Black',
        image: 'darker_than_black.jpg',
        genre: ['Action', 'Mystery', 'Sci-Fi'],
        episodes: 25,
        rating: 8.06,
        type: 'TV',
        gif: 'darker_than_black.gif',
        cruncyroll: 'https://animepahe.com/anime/30417485-ce0c-b4d1-560a-c2a523eacab7',
        youtube: 'https://www.youtube.com/watch?v=upx-_9-RjoE&ab_channel=MokiNS',
        description: 'Darker than Black is a stylish and thrilling anime that follows Hei, a mysterious contractor who possesses supernatural abilities. With its intricate plot, well-crafted action scenes, and exploration of complex themes such as morality and identity, this anime is a must-watch for fans of action, sci-fi, and mystery.',
        url: 'https://myanimelist.net/anime/2025/Darker_than_Black__Kuro_no_Keiyakusha',
    },

    {
        id: 3,
        title: 'Erased',
        image: 'erased.png',
        genre: ['Mystery', 'Supernatural', 'Suspense'],
        episodes: 12,
        rating: 8.31,
        type: 'TV',
        gif: 'erased.gif',
        cruncyroll: 'https://www.crunchyroll.com/series/GYGG92K7Y/erased',
        youtube: 'https://www.youtube.com/watch?v=g8tTxuO1oIY&ab_channel=AniplexUSA',
        description: 'Erased is a gripping and emotionally charged anime that follows Satoru, a man who possesses the ability to travel back in time and prevent tragic events from occurring. With a unique premise, well-developed characters, and a thrilling storyline, "Erased" offers a powerful exploration of friendship, family, and the consequences of our actions.',
        url: 'https://myanimelist.net/anime/31043/Boku_dake_ga_Inai_Machi',
    },

    {
        id: 4,
        title: 'Moriarty the Patriot',
        image: 'moriarty.jpg',
        genre: ['Mystery', 'Suspense'],
        episodes: 11,
        rating: 8.16,
        type: 'TV',
        gif: 'moriarty.gif',
        cruncyroll: 'https://www.crunchyroll.com/series/GXJHM379D/moriarty-the-patriot',
        youtube: 'https://www.youtube.com/watch?v=zDX2dfLqhjo&ab_channel=CrunchyrollDubs',
        description: 'Yuukoku no Moriarty is a sophisticated and engaging anime that follows the notorious Moriarty, the mastermind behind some of the most notorious crimes in history. With its clever writing, well-crafted characters, and exploration of complex themes such as justice and revenge, this anime is a must-watch for fans of mystery, drama, and historical fiction.',
        url: 'https://myanimelist.net/anime/40911/Yuukoku_no_Moriarty',
    },

    {
        id: 5,
        title: 'Promised Neverland',
        image: 'promised_neverland.jpg',
        genre: ['Mystery', 'Sci-Fi', 'Suspense'],
        episodes: 12,
        rating: 8.52,
        type: 'TV',
        gif: 'promised_neverland.gif',
        cruncyroll: 'https://www.crunchyroll.com/series/GYVD2K1WY/the-promised-neverland',
        youtube: 'https://www.youtube.com/watch?v=dJhzDlwvwrI&ab_channel=BiordiFilms',
        description: 'Promised Neverland is a suspenseful and emotionally charged anime that takes place in a seemingly idyllic orphanage that hides a dark secret. With its well-crafted characters, intense suspense, and exploration of themes such as trust, betrayal, and survival, this anime is a must-watch for fans of horror, suspense, and psychological drama.',
        url: 'https://myanimelist.net/anime/37779/Yakusoku_no_Neverland',
    },

    {
        id: 6,
        title: 'Terrror in Resonance',
        image: 'terror_in_resonance.jpg',
        genre: ['Mystery', 'Suspense'],
        episodes: 11,
        rating: 8.1,
        type: 'TV',
        gif: 'terror_in_resonance.gif',
        cruncyroll: 'https://www.crunchyroll.com/series/G675W00MR/terror-in-resonance',
        youtube: 'https://www.youtube.com/watch?v=nLVy50LnLMM',
        description: 'Terror in Resonance is a tense and emotionally charged anime that follows two teenage terrorists who plan to exact revenge on the government. With its well-crafted characters, intense action scenes, and exploration of complex themes such as justice and identity, this anime is a must-watch for fans of drama, thriller, and social commentary.',
        url: 'https://myanimelist.net/anime/23283/Zankyou_no_Terror',
    },
    {
        id: 7,
        title: 'Death Note',
        image: 'death_note.jpg',
        genre: ['Mystery', 'Supernatural', 'Suspense'],
        episodes: 37,
        rating: 8.62,
        type: 'TV',
        gif: 'death_note.gif',
        cruncyroll: 'got.cr/Watch-DeathNote',
        youtube: 'https://www.youtube.com/watch?v=NlJZ-YgAt-c',
        description: 'Death Note is a gripping and intense anime that follows Light Yagami, a high school student who discovers a supernatural notebook that allows him to kill anyone whose name he writes in it. With its unique premise, well-developed characters, and exploration of complex themes such as justice and power, this anime is a must-watch for fans of psychological thriller, crime, and mystery.',
        url: 'https://myanimelist.net/anime/1535/Death_Note',
    },
    {
        id: 8,
        title: 'Steins Gate',
        image: 'steins_gate.jpg',
        genre: ['Drama', 'Sci-Fi', 'Mystery'],
        episodes: 24,
        rating: 9.08,
        type: 'TV',
        gif: 'steins_gate.gif',
        cruncyroll: 'https://www.hulu.com/series/steinsgate-1e6bb91f-1b9f-471e-8bd3-ec7cb0de1869',
        youtube: 'https://www.youtube.com/watch?v=uMYhjVwp0Fk',
        description: 'Steins Gate is a mind-bending and emotionally charged anime that follows a group of scientists who accidentally invent a time machine. With its well-crafted characters, intricate plot, and exploration of complex themes such as time travel and the consequences of our actions, this anime is a must-watch for fans of sci-fi, drama, and suspense.',
        url: 'https://myanimelist.net/anime/9253/Steins_Gate',
    },
    {
        id: 9,
        title: 'Made in Abyss',
        image: 'made_in_abyss.jpg',
        genre: ['Adventure', 'Fantasy', 'Mystery', 'Sci-Fi'],
        episodes: 13,
        rating: 8.66,
        type: 'TV',
        gif: 'made_in_abyss.gif',
        cruncyroll: 'https://www.amazon.com/MADE-IN-ABYSS-Season-1/dp/B073S1Y7BZ',
        youtube: 'https://www.youtube.com/watch?v=kqBNQEUI8dM',
        description: 'Made in Abyss is a visually stunning and emotionally charged anime that follows Riko, a young girl who embarks on a perilous journey to explore the mysterious and dangerous Abyss. With its captivating world-building, well-crafted characters, and exploration of complex themes such as exploration, friendship, and sacrifice, this anime is a must-watch for fans of fantasy, adventure, and drama.',
        url: 'https://myanimelist.net/anime/34599/Made_in_Abyss',
    },
    {
        id: 10,
        title: 'Summertime Render',
        image: 'summertime_render.png',
        genre: ['Mystery', 'Supernatural', 'Suspense'],
        episodes: 25,
        rating: 8.52,
        type: 'TV',
        gif: 'summertime_render.gif',
        cruncyroll: 'https://www.hulu.com/series/summer-time-rendering-5e235d03-75bc-4322-9c10-c2e49a1ca26d',
        youtube: 'https://www.youtube.com/watch?v=Js9ZHbAH3bE',
        description: 'Summer Time Render is a mysterious and intriguing anime that follows a group of high school students who discover a mysterious clock tower that can transport them through time. With its well-crafted characters, intricate plot, and exploration of complex themes such as time travel and the nature of reality, this anime is a must-watch for fans of sci-fi, mystery, and drama.',
        url: 'https://myanimelist.net/anime/47194/Summertime_Render',
    },
]

module.exports = Mystery

