
const Romance = [
    {
        id: 1,
        title: 'Violet Evergarden',
        image: 'violet_evergarden.jpg',
        genre: ['Drama', 'Fantasy'],
        episodes: 13,
        rating: 8.67,
        type: 'TV',
        gif: 'violet_evergarden.gif',
        cruncyroll: 'https://www.netflix.com/gb/title/80182123',
        youtube: 'https://www.youtube.com/watch?v=UZEOpfelkxQ',
        description: 'Violet Evergarden is a stunningly beautiful and emotionally powerful anime that follows the journey of Violet, a former soldier who becomes a ghostwriter. With its breathtaking animation, richly developed characters, and exploration of complex themes such as love, loss, and human connection, this anime is a must-watch for fans of drama, romance, and historical fiction.',
        url: 'https://myanimelist.net/anime/33352/Violet_Evergarden',
    },
    {
        id: 2,
        title: 'Tonikaku Kawaii',
        image: 'tonikaku.jpg',
        genre: ['Comedy', 'Romance'],
        episodes: 12,
        rating: 7.9,
        type: 'TV',
        gif: 'tonikaku.gif',
        cruncyroll: 'https://www.crunchyroll.com/series/GRWMGGQ86/tonikawa-over-the-moon-for-you',
        youtube: 'https://www.youtube.com/watch?v=de9OckSLP1o',
        description: 'Tonikaku Kawaii is a sweet and heartwarming anime that follows the relationship between Nasa, a diligent student, and Tsukasa, a mysterious girl who saves his life. With its charming characters, wholesome humor, and exploration of themes such as love and marriage, this anime is a must-watch for fans of romance, comedy, and slice-of-life.',
        url: 'https://myanimelist.net/anime/41389/Tonikaku_Kawaii',
    },
    {
        id: 3,
        title: 'Toradora',
        image: 'toradora.webp',
        genre: ['Drama', 'Romance'],
        episodes: 25,
        rating: 8.08,
        type: 'TV',
        gif: 'toradora.gif',
        cruncyroll: 'https://www.crunchyroll.com/series/G6P8PXJW6/toradora',
        youtube: 'https://www.youtube.com/watch?v=ya570uUgQNc',
        description: 'Toradora is a classic and beloved anime that follows the relationship between Ryuuji, a gentle and dependable boy, and Taiga, a feisty and fierce girl. With its endearing characters, charming humor, and exploration of themes such as love, friendship, and personal growth, this anime is a must-watch for fans of romance, comedy, and coming-of-age stories.',
        url: 'https://myanimelist.net/anime/4224/Toradora',
    },
    {
        id: 4,
        title: 'My Teen Romantic Comedy SNAFU',
        image: 'yahari.jpg',
        genre: ['Comedy', 'Romance'],
        episodes: 13,
        rating: 8.01,
        type: 'TV',
        gif: 'yahari.gif',
        cruncyroll: 'https://www.crunchyroll.com/series/GYNQJ8GXY/my-teen-romantic-comedy-snafu',
        youtube: 'https://www.youtube.com/watch?v=u-bpwWPNEpE',
        description: 'My Teen Romantic Comedy SNAFU is a smart and introspective anime that follows the journey of Hachiman, a cynical and sharp-witted high school student. With its thought-provoking commentary on social dynamics, well-crafted characters, and exploration of themes such as friendship, identity, and self-acceptance, this anime is a must-watch for fans of drama, comedy, and psychology.',
        url: 'https://myanimelist.net/anime/14813/Yahari_Ore_no_Seishun_Love_Comedy_wa_Machigatteiru',
    },
    {
        id: 5,
        title: '3D Kanojo: Real Girl',
        image: '3d_kanojo.jpg',
        genre: ['Romance'],
        episodes: 12,
        rating: 6.85,
        type: 'TV',
        gif: '3d_kanojo.gif',
        cruncyroll: 'https://www.hidive.com/tv/real-girl',
        youtube: 'https://www.youtube.com/watch?v=4b1Lpm_px04',
        description: '3D Kanojo is a heartfelt and honest anime that follows the relationship between Hikari, a socially awkward boy, and Iroha, a popular girl with a troubled past. With its realistic depiction of teenage romance, relatable characters, and exploration of themes such as acceptance, trust, and communication, this anime is a must-watch for fans of romance, drama, and slice-of-life.',
        url: 'https://myanimelist.net/anime/36793/3D_Kanojo__Real_Girl',
    },
    {
        id: 6,
        title: 'Golden Time',
        image: 'golden_time.jpg',
        genre: ['Comedy', 'Romance'],
        episodes: 24,
        rating: 7.74,
        type: 'TV',
        gif: 'golden_time.gif',
        cruncyroll: 'https://www.hidive.com/tv/golden-time',
        youtube: 'https://www.youtube.com/watch?v=ER8wXRhZW1k',
        description: 'Golden Time is a mature and emotional anime that follows the journey of Tada Banri, a college student who suffers from amnesia. With its well-crafted characters, nuanced exploration of themes such as love, identity, and mental health, and unique setting of college life, this anime is a must-watch for fans of romance, drama, and psychology.',
        url: 'https://myanimelist.net/anime/17895/Golden_Time',
    },
    {
        id: 7,
        title: 'Rent-a-Girlfriend',
        image: 'rent_a_girlfriend.jpg',
        genre: ['Comedy', 'Romance'],
        episodes: 12,
        rating: 7.08,
        type: 'TV',
        gif: 'rent_a_girlfriend.gif',
        cruncyroll: 'https://www.crunchyroll.com/series/G6QWV3976/rent-a-girlfriend',
        youtube: 'https://www.youtube.com/watch?v=jZFEtc3CKHs',
        description: 'Rent a GirlFriend is a fun and entertaining anime that follows the relationship between Kazuya, a lonely and desperate young man, and Chizuru, a beautiful and professional girlfriend-for-hire. With its engaging premise, likable characters, and exploration of themes such as loneliness, self-worth, and personal growth, this anime is a must-watch for fans of romance, comedy, and drama.',
        url: 'https://myanimelist.net/anime/40839/Kanojo_Okarishimasu',
    },
    {
        id:  8 ,
        title: 'Nana',
        image: 'nana.jpg',
        genre:  ['Drama', 'Romance'] ,
        episodes:  47 ,
        rating:  8.54 ,
        type: 'TV',
        gif: 'nana.gif',
        cruncyroll: 'https://www.hidive.com/tv/nana',
        youtube : 'https://www.youtube.com/watch?v=Tad-n4Xh3nI',
        description : 'Nana is a mature and poignant anime that follows the intertwining lives of two women named Nana who become roommates in Tokyo. With its well-developed characters, richly emotional storytelling, and exploration of themes such as love, friendship, and identity, this anime is a must-watch for fans of drama, romance, and music.',
        url: 'https://myanimelist.net/anime/877/Nana',
    }, 
    {
        id: 9,
        title: 'Plastic Memories',
        image: 'plastic_memories.jpg',
        genre: ['Drama', 'Romance', 'Sci-Fi'],
        episodes: 13,
        rating: 7.91,
        type: 'TV',
        gif: 'plastic_memories.gif',
        cruncyroll: 'https://www.crunchyroll.com/series/GRJQVX93Y/plastic-memories',
        youtube: 'https://www.youtube.com/watch?v=vk6mg74R5Ek',
        description: 'Plastic Memories is a heart-wrenching and thought-provoking anime that takes place in a future where androids with limited lifespans are used as companions for humans. With its complex and bittersweet narrative, well-crafted characters, and exploration of themes such as mortality, love, and memory, this anime is a must-watch for fans of sci-fi, drama, and romance.',
        url: 'https://myanimelist.net/anime/27775/Plastic_Memories',
    },
    {
        id: 10,
        title: 'Kokoro Connect',
        image: 'kokoro_connect.jpg',
        genre: ['Drama', 'Romance', 'Supernatural'],
        episodes: 13,
        rating: 7.75,
        type: 'TV',
        gif: 'kokoro_connect.gif',
        cruncyroll: 'https://www.hidive.com/tv/kokoro-connect',
        youtube: 'https://www.youtube.com/watch?v=Mp4jB41pTus',
        description: "Kokoro Connect is a unique high school drama that follows five students who are part of a school club that suddenly switches their bodies at random. Through this experience, they come to learn about each other's hidden emotions and past traumas, strengthening their bonds and learning to support each other. The anime tackles themes of friendship, love, and personal growth in a heartwarming and thought-provoking way.",
        url: 'https://myanimelist.net/anime/11887/Kokoro_Connect',
    },
]

module.exports = Romance;
