
const AnimeList = [
    {
        id: 1,
        title: 'Erased',
        image: 'erased.png',
        genre: ['Mystery', 'Supernatural', 'Suspense'],
        episodes: 12,
        rating: 8.31,
        type: 'TV',
        gif: 'erased.gif',
        crunchyroll: 'https://www.crunchyroll.com/series/GYGG92K7Y/erased',
        youtube: 'https://www.youtube.com/watch?v=g8tTxuO1oIY',
        description: 'Erased is a gripping and emotionally charged anime that follows Satoru, a man who possesses the ability to travel back in time and prevent tragic events from occurring. With a unique premise, well-developed characters, and a thrilling storyline, "Erased" offers a powerful exploration of friendship, family, and the consequences of our actions.',
        url: 'https://myanimelist.net/anime/31043/Boku_dake_ga_Inai_Machi',
    },

    {
        id: 2,
        title: 'Made in Abyss',
        image: 'made_in_abyss.jpg',
        genre: ['Adventure', 'Drama', 'Fantasy', 'Mystery', 'Sci-Fi'],
        episodes: 13,
        rating: 8.66,
        type: 'TV',
        gif: 'made_in_abyss.gif',
        cruncyroll: 'https://animepahe.com/anime/c6848434-0557-8812-2090-88ac2ad23433',
        youtube: 'https://www.youtube.com/watch?v=kqBNQEUI8dM',
        description: 'Made in Abyss is a visually stunning and emotionally compelling anime that explores the mysteries of a massive, deadly chasm known as the Abyss. With an engaging cast of characters, stunning animation, and a haunting soundtrack, this anime is a must-watch for anyone who enjoys adventure, fantasy, and unforgettable storytelling',
        url: 'https://myanimelist.net/anime/34599/Made_in_Abyss',
    },

    {
        id: 3,
        title: 'Code Geass',
        image: 'code_geass.jpg',
        genre: ['Action', 'Award Winning', 'Drama', 'Sci-Fi'],
        episodes: 25,
        rating: 8.7,
        type: 'TV',
        gif: 'code_geass.gif',
        cruncyroll: 'https://animepahe.com/anime/b3141a5b-be42-b47b-6d02-c94a5c1ac806',
        youtube: 'https://www.youtube.com/watch?v=v-AGjx0N24U',
        description: "Code Geass is a thrilling mecha anime that follows Lelouch, a young prince who uses his intelligence and strategic prowess to lead a rebellion against his father's tyrannical empire. With complex characters, intense action, and a gripping storyline, this anime is a must-watch for anyone who enjoys political intrigue, mecha battles, and psychological drama.",
        url: 'https://myanimelist.net/anime/1575/Code_Geass__Hangyaku_no_Lelouch',
    },

    {
        id: 4,
        title: 'Attack on Titan',
        image: 'aot.jpg',
        genre: ['Action', 'Award Winning', 'Drama', 'Suspense'],
        episodes: 25,
        rating: 8.53,
        type: 'TV',
        gif: 'aot.gif',
        cruncyroll: 'https://www.crunchyroll.com/series/GR751KNZY/attack-on-titan',
        youtube: 'https://www.youtube.com/watch?v=MGRm4IzK1SQ',
        description: 'Attack on Titan is a groundbreaking anime that takes place in a world where humanity lives behind massive walls to protect themselves from man-eating giants known as Titans. With its dark and brutal storytelling, breathtaking animation, and memorable characters, this anime is a must-watch for anyone who enjoys epic action, intense drama, and unforgettable twists and turns.',
        url: 'https://myanimelist.net/anime/16498/Shingeki_no_Kyojin',
    },

    {
        id: 5,
        title: 'Kokoro Connect',
        image: 'kokoro_connect.jpg',
        genre: ['Drama', 'Romance', 'Supernatural'],
        episodes: 13,
        rating: 7.75,
        type: 'TV',
        gif: 'kokoro_connect.gif',
        cruncyroll: 'https://animepahe.com/anime/64a47a12-7d08-120c-22e4-7be47b2794d8',
        youtube: 'https://www.youtube.com/watch?v=MnkqA_PRRhM',
        description: 'Kokoro Connect is a unique anime that follows a group of high school students who are suddenly forced to swap bodies with one another. With a blend of drama, romance, and supernatural elements, this anime offers a compelling exploration of identity, friendship, and the struggles of adolescence.',
        url: 'https://myanimelist.net/anime/11887/Kokoro_Connect',
    },

    {
        id: 6,
        title: 'Demon Slayer',
        image: 'demon_slayer.jpg',
        genre: ['Action', 'Award Winning', 'Fantasy'],
        episodes: 26,
        rating: 8.51,
        type: 'TV',
        gif: 'demon_slayer.gif',
        cruncyroll: 'https://www.crunchyroll.com/series/GY5P48XEY/demon-slayer-kimetsu-no-yaiba',
        youtube: 'https://www.youtube.com/watch?v=VQGCKyvzIM4',
        description: 'Demon Slayer is a visually stunning and emotionally gripping anime that follows Tanjiro, a young boy who sets out to avenge his family and protect his sister, who has turned into a demon. With its breathtaking animation, memorable characters, and epic battles, this anime is a must-watch for anyone who enjoys action, fantasy, and emotional storytelling.',
        url: 'https://myanimelist.net/anime/38000/Kimetsu_no_Yaiba',
    },

    {
        id: 7,
        title: 'Mirai Nikki',
        image: 'mirai_nikki.jpg',
        genre: ['Action', 'Supernatural', 'Horror'],
        episodes: 1,
        rating: 7.19,
        type: 'OVA',
        gif: 'mirai_nikki.gif',
        cruncyroll: 'https://animepahe.com/anime/f9ad24bd-12c3-284e-3508-9d8f59c204b8',
        youtube: 'https://www.youtube.com/watch?v=lbAjtMqnRws',
        description: 'Mirai Nikki is a dark and twisted anime that follows Yuki, a high school student who suddenly finds himself thrust into a deadly survival game with twelve other people, all of whom have been given future-seeing diaries. With its complex characters, shocking plot twists, and intense violence, this anime is a must-watch for anyone who enjoys psychological horror and suspense.',
        url: 'https://myanimelist.net/anime/8460/Mirai_Nikki',
    },

    {
        id: 8,
        title: 'Seraph of the End',
        image: 'owari_no_seraph.jpg',
        genre: ['Action', 'Drama', 'Supernatural'],
        episodes: 12,
        rating: 7.49,
        type: 'TV',
        gif: 'owari_no_seraph.gif',
        cruncyroll: 'https://animepahe.com/anime/710bdf18-840c-f273-11ef-a70e05a6f166',
        youtube: 'https://www.youtube.com/watch?v=NtzDAmRhD9s',
        description: 'Owari no Seraph is a post-apocalyptic anime that takes place in a world where a deadly virus has wiped out most of humanity and left behind a world ruled by vampires. With its epic battles, intense action, and memorable characters, this anime offers a unique and thrilling take on the vampire genre that is a must-watch for fans of action and fantasy.',
        url: 'https://myanimelist.net/anime/26243/Owari_no_Seraph',
    },

    {
        id: 9,
        title: 'Tower of God',
        image: 'tower_of_god.jpg',
        genre: ['Action', 'Adventure', 'Drama', 'Fantasy', 'Mystery'],
        episodes: 13,
        rating: 7.56,
        type: 'TV',
        gif: 'tower_of_god.gif',
        cruncyroll: 'https://www.crunchyroll.com/series/G6J0G49DR/tower-of-god',
        youtube: 'https://www.youtube.com/watch?v=RNyClma6awo',
        description: 'Tower of God is a captivating anime that follows Bam, a young boy who enters a mysterious tower in search of his friend. With its complex world-building, well-developed characters, and gripping storyline, this anime offers a unique and engrossing fantasy experience that is a must-watch for fans of adventure and intrigue.',
        url: 'https://myanimelist.net/anime/40221/Kami_no_Tou',
    },

    {
        id: 10,
        title: 'My Teen Romantic Comedy SNAFU',
        image: 'yahari.jpg',
        genre: ['Comedy', 'Romance', 'School'],
        episodes: 13,
        rating: 8.01,
        type: 'TV',
        gif: 'yahari.gif',
        cruncyroll: 'https://animepahe.com/anime/795d3f24-192b-51aa-64f4-bdffa2ae2305',
        youtube: 'https://www.youtube.com/watch?v=u-bpwWPNEpE',
        description: "Yahari is a coming-of-age anime that follows Hachiman, a cynical high school student who finds himself drawn into the world of the school's service club. With its witty dialogue, relatable characters, and exploration of the struggles of adolescence, this anime is a must-watch for anyone who enjoys slice-of-life and romantic comedy.",
        url: 'https://myanimelist.net/anime/14813/Yahari_Ore_no_Seishun_Love_Comedy_wa_Machigatteiru',
    },

]


module.exports = AnimeList;